from src.endpoints.exercises.exercises_api import ExerciseApi
from src.endpoints.workout_plans.workout_plans_api import WorkoutPlansApi
from src.endpoints.weight_tracking.weight_tracking_api import WeightTrackingApi
